name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - mystmd
  - jupyterlab-myst
  - numpy
  - xarray
  - intake
  - matplotlib
  - pytorch-cpu
  - xbatcher
  - rioxarray
  - tqdm
  - pytest
